### ISSUE TITLE
Bug? One too many values passed to format string

### ISSUE THREAD

**Issue by hakanai** [dmgbuild/mac_alias#12]
When reading an alias, the code currently has this:

```
            b.write(struct.pack(b'>hQ4shIIQI14s',
                                self.target.kind,
                                int(voldate * 65536),
                                self.volume.fs_type,
                                self.volume.disk_type,
                                self.target.folder_cnid,
                                self.target.cnid,
                                int(crdate * 65536),
                                self.volume.attribute_flags,
                                self.volume.fs_id,
                                b'\0'*14))
```

Putting the types and what's going in side by side, it looks like there is one more value being put in than the format string should be permitting:

| format chars | value |
| --- | ---------------- |
| `h` | `self.target.kind` |
| `Q` | `int(voldate * 65536)` |
| `4s` | `self.volume.fs_type` |
| `h` | `self.volume.disk_type` |
| `I` | `self.target.folder_cnid` |
| `I` | `self.target.cnid` |
| `Q` | `int(crdate * 65536)` |
| `I` | `self.volume.attribute_flags` |
| `14s` | `self.volume.fs_id` |
| | `b'\0'*14` |

I would hazard a guess that `fs_id` shouldn't be here.

**Comment by freakboy3742** [comment]
@hakanai Definitely looks like `fs_id` is a stray entry - thanks for the report!
