### ISSUE TITLE
Is there perhaps a third format?

### ISSUE THREAD

**Issue by alecmuffett** [dmgbuild/mac_alias#4]
Hi! I just tried this out, and to test it I created a bookmark (Finder>Make Alias) for a screenshot.

I've tried loading it with this code:

```
for file in sys.argv[1:]:
    with open(file) as f:
        b = f.read()
        print 'read bytes:', len(b)
        a = Alias.from_bytes(b)
        print a
```

...and I get either `ValueError('Incorrect alias length')` for Alias, or `ValueError('Not a bookmark file (header size too short)')` for Bookmark.

The hexdump of the start of the alias file, is as follows:

```
$ xdump  Screen*alias
00000000    626f6f6b 00000000 6d61726b 00000000    book....mark....
00000010    38000000 38000000 30030000 00000410    8...8...0.......
00000020    00000000 00600000 068270f0 81f2bf41    .....`....p....A
00000030    00000000 01000000 14020000 04000000    ................
00000040    03030000 00040000 05000000 01010000    ................
00000050    55736572 73000000 05000000 01010000    Users...........
00000060    616c6563 6d000000 07000000 01010000    alecm...........
00000070    4465736b 746f7000 26000000 01010000    Desktop.&.......
00000080    53637265 656e2053 686f7420 32303137    Screen Shot 2017
```

I don't see reference to `book0\0\0\0\mark\0\0\0\0`  in the Bookmark format document, so I am wondering if this is a new, third format?

**Comment by alecmuffett** [comment]
more, here: http://indiestack.com/2017/05/resolving-modern-mac-alias-files/

**Comment by al45tair** [comment]
Yes, there is. `mac_alias` was created to deal with alias and bookmark _records_, not the alias files Finder makes, which have some extra data in them. See also [this older bug report in Bitbucket](https://bitbucket.org/al45tair/mac_alias/issues/3/support-for-version-3-aliases).

**Comment by al45tair** [comment]
FYI, I have added tentative support for alias v3 decoding. I still don't have support for the bookmark file format that this issue is talking about.

**Comment by freakboy3742** [comment]
Closing on the basis that v3 support was evidently added some time ago.

**Comment by hakanai** [comment]
I had a look at the on-disk format and it seems to share a bunch of stuff with the in-memory record format. Type records are basically the same, TOC concept seems to be the same.

![image](https://user-images.githubusercontent.com/43236/207248193-5bd1c817-2b3d-4e9a-8eaf-8c65f30bcf56.png)

https://gist.github.com/hakanai/532deb0b8e3144de5304b206ad5e92b0
